### Create reports
POST http://localhost:3000/reports
content-type: application/json

{
  "make": "Toyota",
  "model": "Corolla",
  "year": 2015,
  "mileage": 10000,
  "lng": 0,
  "lat": 0,
  "price": 500000
}

### Update reports approval status
PATCH http://localhost:3000/reports/2
content-type: application/json

{
  "approved": true
}