### Create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "user@email.com",
  "password": "user"
}

### For Admin
# {
#   "email": "admin@email.com",
#   "password": "admin"
# }

### Sign in
POST http://localhost:3000/auth/signin
content-type: application/json

{
  "email": "user@email.com",
  "password": "user"
}

### WhoAmI
GET http://localhost:3000/auth/whoami

### Sign out
POST http://localhost:3000/auth/signout

### Get user by id
GET http://localhost:3000/auth/66fd5a61-16c4-4416-b6ae-8c9a102742f0	


### Get user list
GET http://localhost:3000/auth

### Get user by their email
GET http://localhost:3000/auth?email=aaa@gmail.com

### Update a user
PATCH http://localhost:3000/auth/66fd5a61-16c4-4416-b6ae-8c9a102742f0	
content-type: application/json

{
  "password": "aaannn"
}

### Deeltete user by id
DELETE http://localhost:3000/auth/7d51dee1-078e-4def-bdaf-44dd16f3594d